using DalamudMCP.Domain.Capabilities;

namespace DalamudMCP.Domain.Registry;

public static class KnownCapabilityRegistry
{
    public static CapabilityRegistry CreateDefault() =>
        new(
            CreateCapabilities(),
            CreateToolBindings(),
            CreateResourceBindings(),
            CreateAddonMetadata());

    private static IReadOnlyList<CapabilityDefinition> CreateCapabilities() =>
        [
            new CapabilityDefinition(
                new CapabilityId("session.status"),
                "Session Status",
                "Read plugin bridge and reader readiness state for diagnostics.",
                CapabilityCategory.System,
                SensitivityLevel.Low,
                ProfileType.Observation,
                defaultEnabled: false,
                requiresConsent: false,
                denied: false,
                supportsTool: true,
                supportsResource: true,
                version: "1.0.0",
                "session",
                "status",
                "diagnostics"),
            new CapabilityDefinition(
                new CapabilityId("player.context"),
                "Player Context",
                "Read coarse self-player context for MCP tools and resources.",
                CapabilityCategory.Player,
                SensitivityLevel.Low,
                ProfileType.Observation,
                defaultEnabled: false,
                requiresConsent: false,
                denied: false,
                supportsTool: true,
                supportsResource: true,
                version: "1.0.0",
                "player",
                "context"),
            new CapabilityDefinition(
                new CapabilityId("duty.context"),
                "Duty Context",
                "Read current duty and territory context.",
                CapabilityCategory.Duty,
                SensitivityLevel.Low,
                ProfileType.Observation,
                defaultEnabled: false,
                requiresConsent: false,
                denied: false,
                supportsTool: true,
                supportsResource: true,
                version: "1.0.0",
                "duty",
                "context"),
            new CapabilityDefinition(
                new CapabilityId("inventory.summary"),
                "Inventory Summary",
                "Read inventory summary data without exposing raw item-by-item detail.",
                CapabilityCategory.Inventory,
                SensitivityLevel.Medium,
                ProfileType.Observation,
                defaultEnabled: false,
                requiresConsent: true,
                denied: false,
                supportsTool: true,
                supportsResource: true,
                version: "1.0.0",
                "inventory",
                "summary"),
            new CapabilityDefinition(
                new CapabilityId("ui.addonCatalog"),
                "Addon Catalog",
                "List observable addons that are currently known to the plugin.",
                CapabilityCategory.Ui,
                SensitivityLevel.Medium,
                ProfileType.Observation,
                defaultEnabled: false,
                requiresConsent: true,
                denied: false,
                supportsTool: true,
                supportsResource: true,
                version: "1.0.0",
                "ui",
                "addons"),
            new CapabilityDefinition(
                new CapabilityId("ui.addonTree"),
                "Addon Tree",
                "Read structural node information from allowlisted addons.",
                CapabilityCategory.Ui,
                SensitivityLevel.Medium,
                ProfileType.Observation,
                defaultEnabled: false,
                requiresConsent: true,
                denied: false,
                supportsTool: true,
                supportsResource: true,
                version: "1.0.0",
                "ui",
                "tree"),
            new CapabilityDefinition(
                new CapabilityId("ui.stringTable"),
                "String Table",
                "Read decoded string table content from allowlisted addons.",
                CapabilityCategory.Ui,
                SensitivityLevel.Medium,
                ProfileType.Observation,
                defaultEnabled: false,
                requiresConsent: true,
                denied: false,
                supportsTool: true,
                supportsResource: true,
                version: "1.0.0",
                "ui",
                "strings"),
            new CapabilityDefinition(
                new CapabilityId("world.nearbyInteractables"),
                "Nearby Interactables",
                "List nearby targetable world objects to support interaction workflows.",
                CapabilityCategory.Target,
                SensitivityLevel.Low,
                ProfileType.Observation,
                defaultEnabled: false,
                requiresConsent: true,
                denied: false,
                supportsTool: true,
                supportsResource: false,
                version: "1.0.0",
                "world",
                "targeting",
                "discovery"),
            new CapabilityDefinition(
                new CapabilityId("world.targetObject"),
                "Target Object",
                "Assign the current target to a specific world object by game object id.",
                CapabilityCategory.Action,
                SensitivityLevel.High,
                ProfileType.Action,
                defaultEnabled: false,
                requiresConsent: true,
                denied: false,
                supportsTool: true,
                supportsResource: false,
                version: "1.0.0",
                "world",
                "targeting",
                "action"),
            new CapabilityDefinition(
                new CapabilityId("world.interactWithTarget"),
                "Interact With Target",
                "Trigger world interaction on the current target after optional target validation.",
                CapabilityCategory.Action,
                SensitivityLevel.High,
                ProfileType.Action,
                defaultEnabled: false,
                requiresConsent: true,
                denied: false,
                supportsTool: true,
                supportsResource: false,
                version: "1.0.0",
                "world",
                "interaction",
                "action"),
            new CapabilityDefinition(
                new CapabilityId("world.moveToEntity"),
                "Move To Entity",
                "Ask an installed navigation provider to move the player toward a specific world object.",
                CapabilityCategory.Action,
                SensitivityLevel.High,
                ProfileType.Action,
                defaultEnabled: false,
                requiresConsent: true,
                denied: false,
                supportsTool: true,
                supportsResource: false,
                version: "1.0.0",
                "world",
                "movement",
                "action"),
            new CapabilityDefinition(
                new CapabilityId("world.teleportToAetheryte"),
                "Teleport To Aetheryte",
                "Teleport the player to an unlocked aetheryte matched by name or alias.",
                CapabilityCategory.Action,
                SensitivityLevel.High,
                ProfileType.Action,
                defaultEnabled: false,
                requiresConsent: true,
                denied: false,
                supportsTool: true,
                supportsResource: false,
                version: "1.0.0",
                "world",
                "teleport",
                "action"),
            new CapabilityDefinition(
                new CapabilityId("ui.addonCallback"),
                "Addon Callback",
                "Send integer callback values to an allowlisted addon.",
                CapabilityCategory.Action,
                SensitivityLevel.High,
                ProfileType.Action,
                defaultEnabled: false,
                requiresConsent: true,
                denied: false,
                supportsTool: true,
                supportsResource: false,
                version: "1.0.0",
                "ui",
                "addon",
                "action"),
        ];

    private static IReadOnlyList<ToolBinding> CreateToolBindings() =>
        [
            new ToolBinding(new CapabilityId("session.status"), "get_session_status", "sessionStatus.input", "sessionStatus.output", "SessionStatusToolHandler", false),
            new ToolBinding(new CapabilityId("player.context"), "get_player_context", "playerContext.input", "playerContext.output", "PlayerContextToolHandler", false),
            new ToolBinding(new CapabilityId("duty.context"), "get_duty_context", "dutyContext.input", "dutyContext.output", "DutyContextToolHandler", false),
            new ToolBinding(new CapabilityId("inventory.summary"), "get_inventory_summary", "inventorySummary.input", "inventorySummary.output", "InventorySummaryToolHandler", false),
            new ToolBinding(new CapabilityId("ui.addonCatalog"), "get_addon_list", "addonCatalog.input", "addonCatalog.output", "AddonListToolHandler", false),
            new ToolBinding(new CapabilityId("ui.addonTree"), "get_addon_tree", "addonTree.input", "addonTree.output", "AddonTreeToolHandler", false),
            new ToolBinding(new CapabilityId("ui.stringTable"), "get_addon_strings", "stringTable.input", "stringTable.output", "AddonStringsToolHandler", false),
            new ToolBinding(new CapabilityId("world.nearbyInteractables"), "get_nearby_interactables", "nearbyInteractables.input", "nearbyInteractables.output", "NearbyInteractablesToolHandler", false),
            new ToolBinding(new CapabilityId("world.targetObject"), "target_object", "targetObject.input", "targetObject.output", "TargetObjectToolHandler", true),
            new ToolBinding(new CapabilityId("world.interactWithTarget"), "interact_with_target", "interactWithTarget.input", "interactWithTarget.output", "InteractWithTargetToolHandler", true),
            new ToolBinding(new CapabilityId("world.moveToEntity"), "move_to_entity", "moveToEntity.input", "moveToEntity.output", "MoveToEntityToolHandler", true),
            new ToolBinding(new CapabilityId("world.teleportToAetheryte"), "teleport_to_aetheryte", "teleportToAetheryte.input", "teleportToAetheryte.output", "TeleportToAetheryteToolHandler", true),
            new ToolBinding(new CapabilityId("ui.addonCallback"), "send_addon_callback_int", "addonCallbackInt.input", "addonCallbackInt.output", "AddonCallbackIntToolHandler", true),
            new ToolBinding(new CapabilityId("ui.addonCallback"), "send_addon_callback_values", "addonCallbackValues.input", "addonCallbackValues.output", "AddonCallbackValuesToolHandler", true),
        ];

    private static IReadOnlyList<ResourceBinding> CreateResourceBindings() =>
        [
            new ResourceBinding(new CapabilityId("session.status"), "ffxiv://session/status", McpContentTypes.ApplicationJson, "SessionStatusResourceProvider", false),
            new ResourceBinding(new CapabilityId("player.context"), "ffxiv://player/context", McpContentTypes.ApplicationJson, "PlayerContextResourceProvider", false),
            new ResourceBinding(new CapabilityId("duty.context"), "ffxiv://duty/context", McpContentTypes.ApplicationJson, "DutyContextResourceProvider", false),
            new ResourceBinding(new CapabilityId("inventory.summary"), "ffxiv://inventory/summary", McpContentTypes.ApplicationJson, "InventorySummaryResourceProvider", false),
            new ResourceBinding(new CapabilityId("ui.addonCatalog"), "ffxiv://ui/addons", McpContentTypes.ApplicationJson, "AddonCatalogResourceProvider", false),
            new ResourceBinding(new CapabilityId("ui.addonTree"), "ffxiv://ui/addon/{addonName}/tree", McpContentTypes.ApplicationJson, "AddonTreeResourceProvider", false),
            new ResourceBinding(new CapabilityId("ui.stringTable"), "ffxiv://ui/addon/{addonName}/strings", McpContentTypes.ApplicationJson, "AddonStringsResourceProvider", false),
        ];

    private static IReadOnlyList<AddonMetadata> CreateAddonMetadata() =>
        [
            new AddonMetadata(
                "Inventory",
                "Inventory",
                CapabilityCategory.Ui,
                SensitivityLevel.Low,
                DefaultEnabled: false,
                Denied: false,
                Recommended: true,
                Notes: "Safe baseline inventory summary and UI tree inspection target.",
                IntrospectionModes: ["tree", "strings"],
                ProfileAvailability: [ProfileType.Observation]),
            new AddonMetadata(
                "Character",
                "Character",
                CapabilityCategory.Ui,
                SensitivityLevel.Low,
                DefaultEnabled: false,
                Denied: false,
                Recommended: true,
                Notes: "Character sheet addon for baseline UI inspection.",
                IntrospectionModes: ["tree", "strings"],
                ProfileAvailability: [ProfileType.Observation]),
            new AddonMetadata(
                "ContentsInfoDetail",
                "Duty Detail",
                CapabilityCategory.Ui,
                SensitivityLevel.Low,
                DefaultEnabled: false,
                Denied: false,
                Recommended: false,
                Notes: "Duty detail panes can be useful for exploratory UI introspection.",
                IntrospectionModes: ["tree", "strings"],
                ProfileAvailability: [ProfileType.Observation]),
        ];
}
